nombre: DemostraciÃ³n de acciones de GitHub
run-name: ${{ github.actor }} estÃ¡ probando GitHub Actions ğŸš€
en: [empujar]
trabajos:
  Explorar acciones de GitHub:
    se ejecuta en: ubuntu-latest
    pasos:
      - ejecutar: echo "ğŸ‰ El trabajo se activÃ³ automÃ¡ticamente mediante un evento ${{ github.event_name }}."
      - run: echo "ğŸ§ Â¡Este trabajo ahora se estÃ¡ ejecutando en un servidor ${{ runner.os }} alojado por GitHub!"
      - ejecutar: echo "ğŸ” El nombre de tu rama es ${{ github.ref }} y tu repositorio es ${{ github.repository }}."
      - nombre: Consultar el cÃ³digo del repositorio
        usos: acciones/checkout@v4
      - run: echo "ğŸ’¡ El repositorio ${{ github.repository }} ha sido clonado al ejecutor."
      - run: echo "ğŸ–¥ï¸ El flujo de trabajo ahora estÃ¡ listo para probar su cÃ³digo en el ejecutor".
      - nombre: Lista los archivos en el repositorio
        correr: |
          ls ${{ github.workspace }}
      - ejecutar: echo "ğŸ El estado de este trabajo es ${{ job.status }}."
